config/routes.rb
Tamada::Application.routes.draw do
  resources :blogs

  mount Rich::Engine => '/rich', :as => 'rich'
  resources :articles

  resources :photos

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :photo_albums

  root 'articles#show', id: 1

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/blog.rb
class Blog < ActiveRecord::Base
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	belongs_to :photo_album
	mount_uploader :photo, PhotoUploader
end

app/models/photo_album.rb
class PhotoAlbum < ActiveRecord::Base
	has_many :photos
	accepts_nested_attributes_for :photos, allow_destroy: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < InheritedResources::Base
end

app/controllers/blogs_controller.rb
class BlogsController < InheritedResources::Base
	def collection
      @blogs ||= end_of_association_chain.order(created_at: :desc)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
	def index
	end
end

app/controllers/photo_albums_controller.rb
class PhotoAlbumsController < InheritedResources::Base
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/photo_albums_helper.rb
module PhotoAlbumsHelper
end

app/views/articles/show.html.haml
%p#notice= notice

%h2
  = @article.name
= raw @article.text

app/views/blogs/index.html.haml
%h2 Записки тамады

- @blogs.each do |blog|
  .row
    .col-lg-1.col-lg-offset-1
      =blog.created_at.strftime("%d.%m.%Y")
    .col-lg-8
      .well
        %h3= blog.title
        = raw blog.text

app/views/blogs/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @blog.title
%p
  %b Text:
  = @blog.text

= link_to 'Edit', edit_blog_path(@blog)
\|
= link_to 'Back', blogs_path

app/views/layouts/application.html.haml
!!!
%html{lang: "en"}
  %head
    %meta{charset: "utf-8"}/
    %meta{content: "IE=Edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "Ведущая Евгения Кривоспицкая"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    = stylesheet_link_tag "application", :media => "all"
    / For third-generation iPad with high-resolution Retina display:
    / Size should be 144 x 144 pixels
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    / For iPhone with high-resolution Retina display:
    / Size should be 114 x 114 pixels
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    / For first- and second-generation iPad:
    / Size should be 72 x 72 pixels
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    / For non-Retina iPhone, iPod Touch, and Android 2.1+ devices:
    / Size should be 57 x 57 pixels
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    / For all other devices
    / Size should be 32 x 32 pixels
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
  %body
    .navbar.navbar-default.navbar-static-top
      .container
        .navbar-header
          %a.navbar-brand{href: "#"} Ведущая Евгения Кривоспицкая
      .container
        .navbar-header
          %ul.nav.navbar-nav
            %li= link_to "Главная", "/"
            %li= link_to "Фото", photo_albums_path
            %li= link_to "Шоу-программы", "/path2"
            %li= link_to "Отзывы", "/path3"
            %li= link_to "Записки тамады", blogs_path
    .container
      .row
        .col-lg-12
          = bootstrap_flash
          = yield
      %footer
        %p © Company 2014

app/views/main/index.html.haml
%h2
  Главная

%container
  %p
    Я ведущая праздничных программ и это моя любимая профессия!
  %p
    8 лет я занимаюсь проведением самых значимых для людей событий, среди которых были:
    %ul
      %li
        свадьбы
      %li
        юбилеи
      %li
        корпоративы и Новогодние вечера
      %li
        открытие торговых центров и магазинов
      %li
        городские праздники
      %li
        детские дни рождения, выпускные и даже спортивный праздник на льду))

  %p
    Я занимаюсь разработкой сценария, написанием текстов и ваш праздник станет уникальным и незабываемым, а главное таким, каким Вы хотите его видеть.

    %p
      Свою работу я выполняю качественно и профессионально, ответственность считаю главным качеством для работы в этом бизнесе. Требовательна ко всем участникам ( ди-джею, оформителям, рестораторам) от которых зависит наше детище, но главным образом к себе! Поэтому постоянно стараюсь совершенствовать свой уровень — занимаюсь вокалом и постановкой голоса, театральным мастерством и сценической речью. В итоге результатом довольны не только мои дорогие клиенты , но даже я:)

app/views/photo_albums/index.html.haml
%h2 Фото-отчеты

- @photo_albums.each do |photo_album|
  .col-lg-3
    =link_to image_tag(photo_album.photos[0].photo.url(:thumb), class: 'img-rounded img-list', style: 'width: 100%;'), photo_album 
  .col-lg-9
    %dl
      %dt= link_to photo_album.name, photo_album 
      %dl= raw photo_album.description
  

app/views/photo_albums/show.html.haml
%p#notice= notice

%h2
  = @photo_album.name
%p
  = raw @photo_album.description

-@photo_album.photos.all.each do |photo|
  .col-lg-3
    =link_to image_tag(photo.photo.url(:thumb), class: 'img-rounded img-list'), photo.photo.url, class: 'fancybox', rel: 'group'